# MACHINE LEARNING

## Vectorization in Machine Learning

In this notebook, we will be looking at usage of numpy and vectorization and how it can decrease computation time for a machine learning algorithm.

In [2]:
import numpy as np
import time

In [3]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4);                print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,));             print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4); print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.35799834 0.06476278 0.62157059 0.78895975], a shape = (4,), a data type = float64


In [4]:
a = np.arange(4.)
print(f"np.arrange(4.) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(4)
print(f"np.random.rand(4) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arrange(4.) : a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4) : a = [0.79807558 0.25766191 0.53208785 0.59337143], a shape = (4,), a data type = float64


In [5]:
a = np.array([5, 4, 3, 2])
print(f"np.array([5, 4, 3, 2]) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5., 4, 3, 1])
print(f"np.array([5., 4, 3, 1]) : a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5, 4, 3, 2]) : a = [5 4 3 2], a shape = (4,), a data type = int32
np.array([5., 4, 3, 1]) : a = [5. 4. 3. 1.], a shape = (4,), a data type = float64


### Indexing of NumPy array

In [9]:
a = np.arange(10)
print(a)

print(f"a[2].shape: {a[2].shape} a[2]: {a[2]}, accessing an element returns a scalar value ")

print(f"last element: {a[-1]}")

try:
    c = a[10]
except Exception as e:
    print(f"Exception: {e}")

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]: 2, accessing an element returns a scalar value 
last element: 9
Exception: index 10 is out of bounds for axis 0 with size 10


### Slicing 

In [10]:
# Vector slicing operations
a = np.arange(10)
print(f"a = {a}")

# access 5 consecutive elements (start, stop, step)
c = a[2:7:1]; print(f"a[2:7:1] = {c}")

# access 3 elements seperated by 2
c = a[2:7:2]; print(f"a[2:7:2] = {c}")

# access all elements index 3 and above
c = a[3:]; print(f"a[3:] = {c}")

# access all elements index 3 and below
c = a[:3]; print(f"a[:3] = {c}")

# access all elements
c = a[:]; print(f"a[:] = {c}") 

a = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] = [2 3 4 5 6]
a[2:7:2] = [2 4 6]
a[3:] = [3 4 5 6 7 8 9]
a[:3] = [0 1 2]
a[:] = [0 1 2 3 4 5 6 7 8 9]


### Single Vector Operations

In [13]:
a = np.array([1,2,3,4, 5])
print(f"a = {a}")

# negate elements of a
b = -a; print(f"b = {b}")

# sum of all elements of a, returns a scalar
b = np.sum(a); print(f"b = {b}")

# mean of a
b = np.mean(a); print(f"b = {b}")

b = a**2; print(f"b = {b}")

a = [1 2 3 4 5]
b = [-1 -2 -3 -4 -5]
b = 15
b = 3.0
b = [ 1  4  9 16 25]


### Vector Vector element wise Operations

In [19]:
a = np.array([1,2,3,4])
b = np.array([1,-2,-3,4])
try:
    print(f"Binary Operations work element wise: {a+b}")
except Exception as e:
    print(f"Exception: {e}")

Binary Operations work element wise: [2 0 0 8]


### Scalar Vector Operations

In [20]:
a = np.array([1,2,3,4])

print(f"5*a: {5*a}")

5*a: [ 5 10 15 20]


### Vector dot product

In [37]:
def my_dot(a, b):
    """
    Compute the dot product of two vectors
    Args:
        a: ndarray(n, ): input vector
        b: ndarray(n, ): input vector
    
    Returns:
        dot_product: scalar
    """
    
    try:
        assert a.shape == b.shape
        x = 0
        for i in range(len(a)):
            x += a[i]*b[i]
        return x
    except:
        print("Error: Arrays must be the same shape")
        return None
    

In [40]:
a = np.array([1,2,3,4])
b = np.array([1,-2,-3,4])
c = my_dot(a, b)

print(f"c = {c}")

c = 4


In [41]:
# dot using np
try:
    c = np.dot(a, b); print(f"a.b = {c}")
    c = np.dot(b, a); print(f"b.a = {c}")
except Exception as e:
    print(f"Exception: {e}")

a.b = 4
b.a = 4


### Comparing vector implementation versus for loop implementation

In [50]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()  # start time
c = np.dot(a, b)
toc = time.time()  # end time

print(f"Vectorized version: {1000*(toc-tic)} ms")
print(f"dot product = {c}")

tic = time.time()  # start time
c = my_dot(a, b)
toc = time.time()  # end time

print(f"Non-vectorized version: {1000*(toc-tic)} ms")
print(f"dot product = {c}")
del(a, b, c)

Vectorized version: 0.9968280792236328 ms
dot product = 250153.50303650688
Non-vectorized version: 412.1725559234619 ms
dot product = 250153.50303650292


In [53]:
# common vector vector operations

X = np.array([[1], [2], [3], [4]])
w = np.array([2])
b = np.dot(X[1], w)

print(f"X[1] has shape = {X[1].shape}")
print(f"w has shape = {w.shape}")
print(f"b has shape = {b.shape}")

X[1] has shape = (1,)
w has shape = (1,)
b has shape = ()


## MATRICES

matrices are two dimensional arrays. The elements of a matrix are all of the same type. Numpy's basic data structure is an indexable n dimensional  *array* containing elements of the same type (`dtype`). Matrices are two-dimensional array of index[m,n]
2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review: 
- data creation
- slicing and indexing

In [54]:
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.53127675]]


In [55]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([[5], [4], [3]]);   print(f" a shape = {a.shape}, np.array: a = {a}")
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); #into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


In [56]:
a = np.arange(6).reshape(-1, 2)
print(f" a shape = {a.shape}, np.arange(6).reshape(-1, 2): a = {a}")

 a shape = (3, 2), np.arange(6).reshape(-1, 2): a = [[0 1]
 [2 3]
 [4 5]]


In [58]:
print(f"\na[2,0].shape: {a[2,0].shape} a[2,0]: {a[2,0]}, accessing an element returns a scalar value ")
print(f"\na[2].shape: {a[2].shape} a[2]: {a[2]}, accessing a row returns a vector ")


a[2,0].shape: () a[2,0]: 4, accessing an element returns a scalar value 

a[2].shape: (2,) a[2]: [4 5], accessing a row returns a vector 


### Slicing 
creates an array of indices using a set of three values

In [63]:
# vector 2D slicing operations
a = np.arange(20).reshape(-1, 10)
print(f"\na = {a}")

# access 5 consecutive elements (start, stop, step)
print(f"a[0, 2:7:1] = {a[0, 2:7:1]}, shape = {a[0, 2:7:1].shape}")

# access 5 consecutive elements (start, stop, step) of two rows
print("a[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")

# access all elements
print("a[:, :] = \n", a[:, :], ",  a[:, :].shape =", a[:, :].shape, "a 2-D array")


a = [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
a[0, 2:7:1] = [2 3 4 5 6], shape = (5,)
a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array
a[:, :] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:, :].shape = (2, 10) a 2-D array


# Multiple Linear Regression

### [*Only for Linear Regression*]
Normal Equation
- Only for Linear Regression
- Solve for w, b without iterations

Disadvantages
- Doesn't generalize to other machine learning algorithms 
- Slow when the number of features are large (n>1000)